/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.cl_pesaje_diario;
import clases.cl_pesaje_trabajador;
import clases.cl_tipo_trabajo;
import clases.cl_trabajadores_sucursal;
import clases.cl_varios;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.m_trabajo;
import objects.o_trabajo;
import pesaje_trabajos.frm_principal;
//rpt_excel_pesaje_diario_trabajador

public class frm_reg_pesaje extends javax.swing.JInternalFrame {

    cl_pesaje_diario c_pesaje_diario = new cl_pesaje_diario();
    cl_varios c_varios = new cl_varios();
    m_trabajo m_trabajo = new m_trabajo();
    cl_trabajadores_sucursal c_trabajadores_sucursal = new cl_trabajadores_sucursal();
    cl_pesaje_trabajador c_pesaje_trabajador = new cl_pesaje_trabajador();
    cl_tipo_trabajo c_tipo = new cl_tipo_trabajo();

    int id_cliente = frm_principal.c_sucursales.getId_cliente();
    int id_sucursal = frm_principal.c_sucursales.getId_sucursal();
    int id_usuario = frm_principal.c_usuario.getId_usuario();

    DefaultTableModel modelo;

    /**
     * Creates new form frm_reg_pesaje
     */
    public frm_reg_pesaje() {
        initComponents();
        ftffecha.setText(c_varios.fecha_usuario(c_varios.getFechaActual()));
        m_trabajo.cbx_trabajo(cbx_trabajo, id_sucursal, id_cliente);
        modelotabla();
    }

    private void modelotabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        modelo.addColumn("Hora");
        modelo.addColumn("Id");
        modelo.addColumn("Colaborador");
        modelo.addColumn("Cantidad");
        t_listrabaj.setModel(modelo);
        t_listrabaj.getColumnModel().getColumn(0).setPreferredWidth(80);
        t_listrabaj.getColumnModel().getColumn(1).setPreferredWidth(40);
        t_listrabaj.getColumnModel().getColumn(2).setPreferredWidth(450);
        t_listrabaj.getColumnModel().getColumn(3).setPreferredWidth(80);
        c_varios.centrar_celda(t_listrabaj, 0);
        c_varios.centrar_celda(t_listrabaj, 1);
        c_varios.derecha_celda(t_listrabaj, 3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftffecha = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        cbx_trabajo = new javax.swing.JComboBox<>();
        btn_iniciar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_colaborador = new javax.swing.JTextField();
        txt_nombrecolaborador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_listrabaj = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btn_guardar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setTitle("Registrar Pesaje Diario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Pesaje"));

        jLabel1.setText("Fecha");

        try {
            ftffecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftffecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftffecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftffechaKeyPressed(evt);
            }
        });

        jLabel2.setText("Tipo Trabajo");

        cbx_trabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PESAJE", "DESTAJO", "CORTE Y FILETE" }));
        cbx_trabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_trabajoMouseClicked(evt);
            }
        });
        cbx_trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_trabajoActionPerformed(evt);
            }
        });
        cbx_trabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_trabajoKeyPressed(evt);
            }
        });

        btn_iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        btn_iniciar.setText("Iniciar");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftffecha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_iniciar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftffecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Colaborador"));

        jLabel3.setText("Colaborador:");

        txt_colaborador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_colaborador.setEnabled(false);
        txt_colaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_colaboradorKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_colaboradorKeyPressed(evt);
            }
        });

        txt_nombrecolaborador.setEditable(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Kg:");

        txt_cantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_cantidad.setEnabled(false);
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyPressed(evt);
            }
        });

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 450, Short.MAX_VALUE)
                        .addComponent(btn_agregar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_colaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombrecolaborador)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_colaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombrecolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Trabajadores"));

        t_listrabaj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:35:02", "1", "ACUÑA CARLOS JOSE ", "3.00"},
                {"09:36:15", "25", "VILLANUEVA ACUÑA JOSE", "15.00"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hora", "ID.", "Colaborador", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(t_listrabaj);
        if (t_listrabaj.getColumnModel().getColumnCount() > 0) {
            t_listrabaj.getColumnModel().getColumn(0).setPreferredWidth(80);
            t_listrabaj.getColumnModel().getColumn(1).setPreferredWidth(50);
            t_listrabaj.getColumnModel().getColumn(2).setPreferredWidth(400);
            t_listrabaj.getColumnModel().getColumn(3).setPreferredWidth(80);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setOpaque(false);

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setEnabled(false);
        btn_guardar.setFocusable(false);
        btn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_guardar);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        jButton4.setText("Salir");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        Object fila[] = new Object[4];
        fila[0] = c_varios.getHoraActual();
        fila[1] = txt_colaborador.getText();
        fila[2] = txt_nombrecolaborador.getText();
        fila[3] = txt_cantidad.getText();
        modelo.addRow(fila);

        //ingresar a la base de datos
        c_pesaje_trabajador.setId_cliente(id_cliente);
        c_pesaje_trabajador.setId_sucursal(id_sucursal);
        c_pesaje_trabajador.setHora(c_varios.getHoraActual());
        c_pesaje_trabajador.setId_trabajador(Integer.parseInt(txt_colaborador.getText()));
        c_pesaje_trabajador.setCantidad(Double.parseDouble(txt_cantidad.getText()));
        c_pesaje_trabajador.setId_pesaje(c_pesaje_diario.getId_pesaje());
        c_pesaje_trabajador.registrar();

        //limpiar campos
        txt_colaborador.setText("");
        txt_nombrecolaborador.setText("");
        txt_cantidad.setText("");
        btn_guardar.setEnabled(true);
        txt_colaborador.requestFocus();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed

        c_pesaje_diario.setId_sucursal(id_sucursal);
        c_pesaje_diario.setId_cliente(id_cliente);
        c_pesaje_diario.setFecha(c_varios.fecha_myql(ftffecha.getText()));
        o_trabajo o_trabajo = (o_trabajo) cbx_trabajo.getSelectedItem();
        c_pesaje_diario.setId_tipo_trabajo(o_trabajo.getId_tipo_trabajo());
        c_pesaje_diario.setId_usuario(id_usuario);
        c_pesaje_diario.obtener_codigo();
        if (c_pesaje_diario.registrar()) {
            //obtener tope de tipo trabajo seleccionado
            c_tipo.setId_cliente(c_pesaje_diario.getId_pesaje());
            c_tipo.setId_sucursal(c_pesaje_diario.getId_sucursal());
            c_tipo.setId_tipo_trabajo(c_pesaje_diario.getId_tipo_trabajo());
            c_tipo.obtener_datos();

            ftffecha.setEnabled(false);
            cbx_trabajo.setEnabled(false);
            btn_iniciar.setEnabled(false);
            txt_colaborador.setText("");
            txt_nombrecolaborador.setText("");
            txt_cantidad.setText("");
            txt_colaborador.requestFocus();
            txt_cantidad.enable(true);
            txt_colaborador.enable(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error!");
        }

    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void cbx_trabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_trabajoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_trabajoMouseClicked

    private void cbx_trabajoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_trabajoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_iniciar.requestFocus();
        }
    }//GEN-LAST:event_cbx_trabajoKeyPressed

    private void cbx_trabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_trabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_trabajoActionPerformed

    private void txt_colaboradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_colaboradorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_colaborador.getText().length() > 0) {
                int colaborador = Integer.parseInt(txt_colaborador.getText());
                c_trabajadores_sucursal.setId_trabajador(colaborador);
                c_trabajadores_sucursal.setId_cliente(id_cliente);
                c_trabajadores_sucursal.setId_sucursal(id_sucursal);

                if (c_trabajadores_sucursal.cargar_datos()) {
                    txt_nombrecolaborador.setText(c_trabajadores_sucursal.getColaborador());
                    txt_cantidad.setEnabled(true);
                    txt_cantidad.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "No existe Trabajor");
                    txt_colaborador.setText("");
                    txt_colaborador.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txt_colaboradorKeyPressed

    private void txt_cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_cantidad.getText().length() > 0) {
                String tcantidad = txt_cantidad.getText();
                if (c_varios.esDecimal(tcantidad)) {
                    double dcantidad = Double.parseDouble(tcantidad);
                    if (dcantidad <= c_tipo.getTope()) {
                        btn_agregar.doClick();
                    } else {
                        JOptionPane.showMessageDialog(null, "ESTE NUMERO ES MAYOR AL TOPE");
                        txt_cantidad.selectAll();
                        txt_cantidad.requestFocus();
                    }
                }
            }
        }
    }//GEN-LAST:event_txt_cantidadKeyPressed

    private void txt_colaboradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_colaboradorKeyTyped
        c_varios.solo_numeros(evt);
        c_varios.limitar_caracteres(evt, txt_colaborador, 3);
    }//GEN-LAST:event_txt_colaboradorKeyTyped

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
//        int contar_filas = t_listrabaj.getRowCount();
//        for (int i = 0; i < contar_filas; i++) {
//            c_pesaje_trabajador.setId_cliente(id_cliente);
//            c_pesaje_trabajador.setId_sucursal(id_sucursal);
//            c_pesaje_trabajador.setHora(t_listrabaj.getValueAt(i, 0).toString());
//            c_pesaje_trabajador.setId_trabajador(Integer.parseInt(t_listrabaj.getValueAt(i, 1).toString()));
//            c_pesaje_trabajador.setCantidad(Double.parseDouble(t_listrabaj.getValueAt(i, 3).toString()));
//            c_pesaje_trabajador.setId_pesaje(c_pesaje_diario.getId_pesaje());
//            c_pesaje_trabajador.registrar();
//        }
//
//        this.dispose();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void ftffechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftffechaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (ftffecha.getText().length() == 10) {
                cbx_trabajo.requestFocus();
            }
        }
    }//GEN-LAST:event_ftffechaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JComboBox<String> cbx_trabajo;
    private javax.swing.JFormattedTextField ftffecha;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable t_listrabaj;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_colaborador;
    private javax.swing.JTextField txt_nombrecolaborador;
    // End of variables declaration//GEN-END:variables
}
