/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.cl_memoramdo;
import clases.cl_pesaje_trabajador;
import clases.cl_tipo_trabajo;
import clases.cl_trabajadores_sucursal;
import clases.cl_varios;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.m_trabajo;
import objects.o_trabajo;
import pesaje_trabajos.frm_principal;
//rpt_excel_pesaje_diario_trabajador

public class frm_reg_pesaje extends javax.swing.JInternalFrame {

    cl_varios c_varios = new cl_varios();
    m_trabajo m_trabajo = new m_trabajo();
    cl_trabajadores_sucursal c_trabajadores_sucursal = new cl_trabajadores_sucursal();
    cl_pesaje_trabajador c_pesaje_trabajador = new cl_pesaje_trabajador();
    cl_tipo_trabajo c_tipo = new cl_tipo_trabajo();
    cl_memoramdo c_memoramdo = new cl_memoramdo();

    int id_cliente = frm_principal.c_sucursales.getId_cliente();
    int id_sucursal = frm_principal.c_sucursales.getId_sucursal();
    int id_usuario = frm_principal.c_usuario.getId_usuario();

    double dneto;

    DefaultTableModel modelo;

    /**
     * Creates new form frm_reg_pesaje
     */
    public frm_reg_pesaje() {
        initComponents();
        ftffecha.setText(c_varios.fecha_usuario(c_varios.getFechaActual()));
        m_trabajo.cbx_trabajo(cbx_trabajo, id_sucursal, id_cliente);
        modelotabla();
    }

    private void modelotabla() {
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Id");
        modelo.addColumn("Colaborador");
        modelo.addColumn("Cantidad");
        t_listrabaj.setModel(modelo);
        t_listrabaj.getColumnModel().getColumn(0).setPreferredWidth(80);
        t_listrabaj.getColumnModel().getColumn(1).setPreferredWidth(80);
        t_listrabaj.getColumnModel().getColumn(2).setPreferredWidth(40);
        t_listrabaj.getColumnModel().getColumn(3).setPreferredWidth(450);
        t_listrabaj.getColumnModel().getColumn(4).setPreferredWidth(80);
        c_varios.centrar_celda(t_listrabaj, 0);
        c_varios.centrar_celda(t_listrabaj, 1);
        c_varios.centrar_celda(t_listrabaj, 2);
        c_varios.derecha_celda(t_listrabaj, 4);

    }

    private void limpiar() {
        txt_colaborador.setText("");
        txt_nombrecolaborador.setText("");
        txt_cantidad.setText("");
        txt_colaborador.requestFocus();
        c_trabajadores_sucursal.setId_trabajador(0);
        desactivar_botones_trabajador();
    }

    private void activar_botones_trabajador() {
        jButton7.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton6.setEnabled(true);
        jButton5.setEnabled(true);
    }

    private void desactivar_botones_trabajador() {
        jButton7.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton6.setEnabled(false);
        jButton5.setEnabled(false);
    }

    private boolean validar_trabajador() {
        if (c_trabajadores_sucursal.getId_trabajador() > 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "NO HA INGRESADO CODIGO DE TRABAJADOR");
            desactivar_botones_trabajador();
            txt_colaborador.requestFocus();
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_detalle_trabajador = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_detalle_trabajador = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jd_memorandum = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftffecha = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        cbx_trabajo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_tope = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_colaborador = new javax.swing.JTextField();
        txt_nombrecolaborador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        txt_tara_balanza = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_neto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_listrabaj = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jd_detalle_trabajador.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jd_detalle_trabajador.setTitle("ver detalle de Pesaje de Trabajador");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Trabajador:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha.");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tipo Trabajo.:");

        t_detalle_trabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(t_detalle_trabajador);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Total Pesaje:");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jd_detalle_trabajadorLayout = new javax.swing.GroupLayout(jd_detalle_trabajador.getContentPane());
        jd_detalle_trabajador.getContentPane().setLayout(jd_detalle_trabajadorLayout);
        jd_detalle_trabajadorLayout.setHorizontalGroup(
            jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_detalle_trabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(jd_detalle_trabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3))
                    .addGroup(jd_detalle_trabajadorLayout.createSequentialGroup()
                        .addGroup(jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addGroup(jd_detalle_trabajadorLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jd_detalle_trabajadorLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jd_detalle_trabajadorLayout.setVerticalGroup(
            jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_detalle_trabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_detalle_trabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        jd_memorandum.setTitle("Agregar Llamada de Atencion al Trabajador");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Trabajador:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Fecha:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Descripcion:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jTextField5.setEditable(false);

        jTextField6.setEditable(false);

        jToolBar1.setFloatable(false);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        jButton4.setText("Grabar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        javax.swing.GroupLayout jd_memorandumLayout = new javax.swing.GroupLayout(jd_memorandum.getContentPane());
        jd_memorandum.getContentPane().setLayout(jd_memorandumLayout);
        jd_memorandumLayout.setHorizontalGroup(
            jd_memorandumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_memorandumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_memorandumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jd_memorandumLayout.createSequentialGroup()
                        .addGroup(jd_memorandumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_memorandumLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 311, Short.MAX_VALUE))
                    .addGroup(jd_memorandumLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5)))
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_memorandumLayout.setVerticalGroup(
            jd_memorandumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_memorandumLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_memorandumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_memorandumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        setClosable(true);
        setTitle("Registrar Pesaje Diario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Pesaje"));

        jLabel1.setText("Tipo de Trabajo:");

        try {
            ftffecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftffecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftffecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ftffechaKeyPressed(evt);
            }
        });

        jLabel2.setText("Fecha");

        cbx_trabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PESAJE", "DESTAJO", "CORTE Y FILETE" }));
        cbx_trabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_trabajoMouseClicked(evt);
            }
        });
        cbx_trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_trabajoActionPerformed(evt);
            }
        });
        cbx_trabajo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_trabajoKeyPressed(evt);
            }
        });

        jLabel5.setText("Tope:");

        txt_tope.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tope.setText("0.00");
        txt_tope.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_topeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(ftffecha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tope, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ftffecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tope, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Colaborador"));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Colaborador:");

        txt_colaborador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_colaborador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_colaborador.setEnabled(false);
        txt_colaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_colaboradorKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_colaboradorKeyPressed(evt);
            }
        });

        txt_nombrecolaborador.setEditable(false);
        txt_nombrecolaborador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Peso - Cantidad:");

        txt_cantidad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_cantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_cantidad.setEnabled(false);
        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyPressed(evt);
            }
        });

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setEnabled(false);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        txt_tara_balanza.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_tara_balanza.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_tara_balanza.setText("0.00");
        txt_tara_balanza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tara_balanzaKeyTyped(evt);
            }
        });

        jLabel6.setText("=");

        jLabel7.setText("-");

        txt_neto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_neto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_neto.setText("0.00");
        txt_neto.setEnabled(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.setEnabled(false);
        jButton2.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/application_edit.png"))); // NOI18N
        jButton8.setText("Modificar");
        jButton8.setEnabled(false);
        jButton8.setMargin(new java.awt.Insets(2, 5, 2, 5));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trash_16.png"))); // NOI18N
        jButton9.setText("Eliminar");
        jButton9.setEnabled(false);
        jButton9.setMargin(new java.awt.Insets(2, 5, 2, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tara_balanza, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_neto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                        .addComponent(btn_agregar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_colaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombrecolaborador)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_colaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_nombrecolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tara_balanza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_neto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Trabajadores"));

        t_listrabaj.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"09:35:02", "1", "ACUÑA CARLOS JOSE ", "3.00"},
                {"09:36:15", "25", "VILLANUEVA ACUÑA JOSE", "15.00"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hora", "ID.", "Colaborador", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(t_listrabaj);
        if (t_listrabaj.getColumnModel().getColumnCount() > 0) {
            t_listrabaj.getColumnModel().getColumn(0).setPreferredWidth(80);
            t_listrabaj.getColumnModel().getColumn(1).setPreferredWidth(50);
            t_listrabaj.getColumnModel().getColumn(2).setPreferredWidth(400);
            t_listrabaj.getColumnModel().getColumn(3).setPreferredWidth(80);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/chart_bar.png"))); // NOI18N
        jButton1.setText("ver Total Kg.");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/user_thief_baldie.png"))); // NOI18N
        jButton7.setText("<html><center>ver Total Trabajador.</center></html>");
        jButton7.setEnabled(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/error.png"))); // NOI18N
        jButton3.setText("<html><center>Llamada Atencion</center></html>");
        jButton3.setEnabled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pagos.png"))); // NOI18N
        jButton6.setText("Descuento");
        jButton6.setEnabled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clipboard_text.png"))); // NOI18N
        jButton5.setText("<html><center>ver pesajes del Trabajador</center></html>");
        jButton5.setEnabled(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        Object fila[] = new Object[5];
        fila[0] = c_varios.fecha_myql(ftffecha.getText());
        fila[1] = c_varios.getHoraActual();
        fila[2] = txt_colaborador.getText();
        fila[3] = txt_nombrecolaborador.getText();
        fila[4] = c_varios.formato_numero(dneto);
        modelo.addRow(fila);

        //ingresar a la base de datos
        c_pesaje_trabajador.setId_cliente(id_cliente);
        c_pesaje_trabajador.setId_sucursal(id_sucursal);
        c_pesaje_trabajador.setHora(c_varios.getHoraActual());
        c_pesaje_trabajador.setId_trabajador(Integer.parseInt(txt_colaborador.getText()));
        c_pesaje_trabajador.setCantidad(dneto);
        c_pesaje_trabajador.setFecha(c_varios.fecha_myql(ftffecha.getText()));
        c_pesaje_trabajador.setId_tipo_trabajo(c_tipo.getId_tipo_trabajo());
        c_pesaje_trabajador.registrar();

        //limpiar campos
        limpiar();
        txt_colaborador.setText("");
        txt_nombrecolaborador.setText("");
        txt_cantidad.setText("");
        txt_colaborador.requestFocus();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void cbx_trabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_trabajoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_trabajoMouseClicked

    private void cbx_trabajoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_trabajoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // btn_iniciar.requestFocus();
            o_trabajo o_trabajo = (o_trabajo) cbx_trabajo.getSelectedItem();

            c_tipo.setId_cliente(id_cliente);
            c_tipo.setId_sucursal(id_sucursal);
            c_tipo.setId_tipo_trabajo(o_trabajo.getId_tipo_trabajo());
            c_tipo.obtener_datos();

            txt_tope.setText(c_varios.formato_numero(c_tipo.getTope()));

            //mostrar datos grabados 
            modelotabla();

            c_pesaje_trabajador.setFecha(c_varios.fecha_myql(ftffecha.getText()));
            c_pesaje_trabajador.setId_cliente(id_cliente);
            c_pesaje_trabajador.setId_sucursal(id_sucursal);
            c_pesaje_trabajador.setId_tipo_trabajo(o_trabajo.getId_tipo_trabajo());
            c_pesaje_trabajador.ver_pesaje_fecha(modelo);
            t_listrabaj.setModel(modelo);

            txt_colaborador.setEnabled(true);
            txt_colaborador.requestFocus();
        }
    }//GEN-LAST:event_cbx_trabajoKeyPressed

    private void cbx_trabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_trabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_trabajoActionPerformed

    private void txt_colaboradorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_colaboradorKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_colaborador.getText().length() > 0) {
                int colaborador = Integer.parseInt(txt_colaborador.getText());
                c_trabajadores_sucursal.setId_trabajador(colaborador);
                c_trabajadores_sucursal.setId_cliente(id_cliente);
                c_trabajadores_sucursal.setId_sucursal(id_sucursal);

                if (c_trabajadores_sucursal.cargar_datos()) {
                    txt_nombrecolaborador.setText(c_trabajadores_sucursal.getColaborador());

                    //activar botones trabajador
                    activar_botones_trabajador();

                    txt_cantidad.setEnabled(true);
                    txt_cantidad.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "No existe Trabajor");
                    txt_colaborador.setText("");
                    txt_colaborador.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txt_colaboradorKeyPressed

    private void txt_cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txt_cantidad.getText().length() > 0) {
                String tara = txt_tara_balanza.getText();
                double dtara = 0;
                if (c_varios.esDecimal(tara)) {
                    dtara = Double.parseDouble(tara);
                }

                String pesaje = txt_cantidad.getText();
                double dcantidad;

                dneto = 0;

                if (c_varios.esDecimal(pesaje)) {
                    dcantidad = Double.parseDouble(pesaje);

                    dneto = dcantidad - dtara;
                    txt_neto.setText(c_varios.formato_numero(dneto));

                    if (dneto <= c_tipo.getTope()) {
                        btn_agregar.setEnabled(true);
                        btn_agregar.doClick();
                    } else {
                        JOptionPane.showMessageDialog(null, "ESTE NUMERO ES MAYOR AL TOPE");
                        // txt_cantidad.selectAll();
                        //txt_cantidad.requestFocus();
                        btn_agregar.setEnabled(true);
                        btn_agregar.requestFocus();
                        //btn_agregar.doClick();
                    }
                }
            }
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            limpiar();
        }
    }//GEN-LAST:event_txt_cantidadKeyPressed

    private void txt_colaboradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_colaboradorKeyTyped
        c_varios.solo_numeros(evt);
        c_varios.limitar_caracteres(evt, txt_colaborador, 3);
    }//GEN-LAST:event_txt_colaboradorKeyTyped

    private void ftffechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftffechaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (ftffecha.getText().length() == 10) {
                cbx_trabajo.requestFocus();
            }
        }
    }//GEN-LAST:event_ftffechaKeyPressed

    private void txt_topeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_topeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txt_tope.getText();
            if (c_varios.esDecimal(texto)) {
                c_tipo.setTope(Double.parseDouble(texto));
                c_tipo.actualizar();
                txt_colaborador.setEnabled(true);
                txt_colaborador.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_topeKeyPressed

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
        c_varios.solo_precio(evt);
        c_varios.limitar_caracteres(evt, txt_cantidad, 8);
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void txt_tara_balanzaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tara_balanzaKeyTyped
        c_varios.solo_precio(evt);
        c_varios.limitar_caracteres(evt, txt_tara_balanza, 8);
    }//GEN-LAST:event_txt_tara_balanzaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c_pesaje_trabajador.setFecha(c_varios.fecha_myql(ftffecha.getText()));
        double total = c_pesaje_trabajador.obtener_total_fecha();

        JOptionPane.showMessageDialog(null, "<html>El pesaje total del dia es: <h2>" + c_varios.formato_numero(total) + "</h2></html>");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (validar_trabajador()) {
            c_pesaje_trabajador.setId_trabajador(c_trabajadores_sucursal.getId_trabajador());
            double total = c_pesaje_trabajador.obtener_total_trabajador_fecha();

            JOptionPane.showMessageDialog(null, "<html>El pesaje total del trabajador es: <h2>" + c_varios.formato_numero(total) + "</h2></html>");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpiar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jd_detalle_trabajador.setModal(true);
        jd_detalle_trabajador.setSize(436, 474);

        c_pesaje_trabajador.setId_trabajador(c_trabajadores_sucursal.getId_trabajador());
        c_pesaje_trabajador.ver_detalle_trabajador(t_detalle_trabajador);

        jTextField1.setText(txt_nombrecolaborador.getText());
        jTextField2.setText(ftffecha.getText());
        jTextField3.setText(c_tipo.getDescripcion());

        double total = 0;
        for (int i = 0; i < t_detalle_trabajador.getRowCount(); i++) {
            total += Double.parseDouble(t_detalle_trabajador.getValueAt(i, 2).toString());
        }

        jTextField4.setText(c_varios.formato_totales(total));

        jd_detalle_trabajador.setLocationRelativeTo(null);
        jd_detalle_trabajador.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTextArea1.getText().length() > 0) {
            c_memoramdo.setContenido(jTextArea1.getText());
            c_memoramdo.setFecha(c_varios.fecha_myql(ftffecha.getText()));
            c_memoramdo.setId_cliente(id_cliente);
            c_memoramdo.setId_sucursal(id_sucursal);
            c_memoramdo.setId_trabajador(c_trabajadores_sucursal.getId_trabajador());
            c_memoramdo.obtener_codigo();

            if (c_memoramdo.registrar()) {
                int contar_memos = c_memoramdo.contar_memos();
                if (contar_memos >= 3) {
                    JOptionPane.showMessageDialog(null, txt_nombrecolaborador.getText() + " YA TIENE 03 LLAMADAS DE ATENCION", "Maximo de Llamadas de Atencion", 1, frameIcon);
                }
                jd_memorandum.dispose();
                
                txt_colaborador.requestFocus();
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jd_memorandum.setModal(true);
        jd_memorandum.setSize(578, 440);
        
        jTextField5.setText(txt_nombrecolaborador.getText());
        jTextField6.setText(ftffecha.getText());
        jTextArea1.requestFocus();

        jd_memorandum.setLocationRelativeTo(null);
        jd_memorandum.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JComboBox<String> cbx_trabajo;
    private javax.swing.JFormattedTextField ftffecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog jd_detalle_trabajador;
    private javax.swing.JDialog jd_memorandum;
    private javax.swing.JTable t_detalle_trabajador;
    private javax.swing.JTable t_listrabaj;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_colaborador;
    private javax.swing.JTextField txt_neto;
    private javax.swing.JTextField txt_nombrecolaborador;
    private javax.swing.JTextField txt_tara_balanza;
    private javax.swing.JTextField txt_tope;
    // End of variables declaration//GEN-END:variables
}
