package formularios;

import clases.cl_tipo_trabajo;
import clases.cl_varios;
import java.awt.event.KeyEvent;
import pesaje_trabajos.frm_principal;
import vistas.frm_ver_tipo_servicio;

/**
 *
 * @author KALEK
 */
public class frm_reg_trabajo extends javax.swing.JInternalFrame {

    cl_varios c_varios = new cl_varios();
    public static cl_tipo_trabajo c_tipo_trabajo = new cl_tipo_trabajo();

    public static boolean registrar;

    int id_cliente = frm_principal.c_sucursales.getId_cliente();
    int id_sucursal = frm_principal.c_sucursales.getId_sucursal();
    int id_usuario = frm_principal.c_usuario.getId_usuario();

    /**
     * Creates new form frm_reg_trabajo
     */
    public frm_reg_trabajo() {
        initComponents();

        if (!registrar) {
            c_tipo_trabajo.setId_cliente(frm_principal.c_sucursales.getId_cliente());
            c_tipo_trabajo.setId_sucursal(frm_principal.c_sucursales.getId_sucursal());
            c_tipo_trabajo.obtener_datos();
            txtdescripcion.setText(c_tipo_trabajo.getDescripcion());
            txtpreciokg.setText(c_tipo_trabajo.getPreciokg() + "");
            txt_tope.setText(c_tipo_trabajo.getTope() + "");
            txtdescripcion.setEnabled(true);
            txtpreciokg.setEnabled(true);
            txt_tope.setEnabled(true);
            btn_modificar.setEnabled(true);
            btn_guardar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_guardar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtdescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtpreciokg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_tope = new javax.swing.JTextField();

        setTitle("Agregar Tipo de trabajo");

        jToolBar1.setFloatable(false);
        jToolBar1.setOpaque(false);

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/accept.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setEnabled(false);
        btn_guardar.setFocusable(false);
        btn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_guardar);

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/application_edit.png"))); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.setEnabled(false);
        btn_modificar.setFocusable(false);
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_modificar);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        txtdescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyPressed(evt);
            }
        });

        jLabel1.setText("Descripcion:");

        jLabel4.setText("PrecioxKG:");

        txtpreciokg.setEnabled(false);
        txtpreciokg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpreciokgKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpreciokgKeyPressed(evt);
            }
        });

        jLabel2.setText("Tope:");

        txt_tope.setEnabled(false);
        txt_tope.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_topeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpreciokg, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tope, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpreciokg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tope, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        //capturar a la bd de sistema
        c_tipo_trabajo.setDescripcion(txtdescripcion.getText());
        c_tipo_trabajo.setId_cliente(frm_principal.c_sucursales.getId_cliente());
        c_tipo_trabajo.setId_sucursal(frm_principal.c_sucursales.getId_sucursal());
        c_tipo_trabajo.setPreciokg(Double.parseDouble(txtpreciokg.getText()));
        c_tipo_trabajo.setTope(Double.parseDouble(txt_tope.getText()));
        c_tipo_trabajo.obtener_codigo();
        boolean registrado = c_tipo_trabajo.registrar();

        if (registrado) {
            this.dispose();
            frm_ver_tipo_servicio formulario = new frm_ver_tipo_servicio();
            c_varios.llamar_ventana(formulario);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed

        c_tipo_trabajo.setDescripcion(txtdescripcion.getText());
        c_tipo_trabajo.setId_cliente(frm_principal.c_sucursales.getId_cliente());
        c_tipo_trabajo.setId_sucursal(frm_principal.c_sucursales.getId_sucursal());
        c_tipo_trabajo.setPreciokg(Double.parseDouble(txtpreciokg.getText()));
        c_tipo_trabajo.setTope(Double.parseDouble(txt_tope.getText()));

        boolean actualizado = c_tipo_trabajo.actualizar();

        if (actualizado) {
            this.dispose();
            frm_ver_tipo_servicio formulario = new frm_ver_tipo_servicio();
            c_varios.llamar_ventana(formulario);
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        frm_ver_tipo_servicio formulario = new frm_ver_tipo_servicio();
        c_varios.llamar_ventana(formulario);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtdescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtdescripcion.getText().length() > 0) {
                txtpreciokg.setEnabled(true);
                txtpreciokg.requestFocus();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionKeyPressed

    private void txtpreciokgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpreciokgKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtpreciokg.getText().length() > 0) {
                txt_tope.setEnabled(true);
                txt_tope.requestFocus();
            }
        }

    }//GEN-LAST:event_txtpreciokgKeyPressed

    private void txtpreciokgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpreciokgKeyTyped

        String text = txtpreciokg.getText();
        double dprecio = 0;
        if (c_varios.esDecimal(text)) {
            dprecio = Double.parseDouble(text);
        }
    }//GEN-LAST:event_txtpreciokgKeyTyped

    private void txt_topeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_topeKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (registrar) {
                if (txt_tope.getText().length() > 0) {
                    btn_guardar.setEnabled(true);
                }
            }
        }

    }//GEN-LAST:event_txt_topeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txt_tope;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtpreciokg;
    // End of variables declaration//GEN-END:variables
}
